### ISSUE TITLE
Disentangle `params` and `meta` in db/*.yml manifests

### ISSUE THREAD

**Issue by jhunt** [genesis-community/cf-genesis-kit#24]
In the post 2.6 version of the CF kit, we have some clean up to do.  The primary offense so far has been an apparent abuse of `params` vs. `meta`.  We should stop using `params` for anything we are not actively expecting the operators to want to override.

For example, in `db/local.yml`, we have params for the various db hosts, even though they are all supposed to be pulled from an instance_group static IP.  Let's make this divide more pronounced, and put our "internal arguments" in `meta`, and populate `meta` from `params` where appropriate (i.e. when translating external db host IPs into the uaadb/ccdb/diegodb configuration settings).

**Comment by Proplex** [comment]
I'll take this ticket. I plan to gut all references to `param` unless it's an operator-definable setting, otherwise it's a `meta`

Furthermore, all `meta` fields will be in a new `meta.yml` which will store _all_ references to `meta`, including the previously defined `certs.yml` which handled `meta.certs`
