### ISSUE TITLE
autogenerated haproxy cert does not create SANs based on apps_domain and system_domain

### ISSUE THREAD

**Issue by thomasmmitchell** [genesis-community/cf-genesis-kit#39]
If apps_domain and system_domain are overridden, the SANs on the haproxy certs should also be generated to reflect these.

**Comment by dennisjbell** [comment]
We already closed this with won't-fix: rationale is that if you're advanced/customized enough to change your domains, you're advanced enough to use your own certs instead of default self-signed.

There are technical reasons why we can't do this without significant rework and hoop-jumping, and genesis is opinionated software that doesn't like it when you deviate from the norm (it allows it, but expect to do more work on your part) 

See https://github.com/genesis-community/cf-genesis-kit/issues/31#issuecomment-415822554
